[metadata]
creation_date = "2024/09/21"
maturity = "development"
updated_date = "2024/09/21"

[rule]
author = ["sam"]
description = "Detection of netsh.exe usage"
language = "eql"
name = "Detect Netsh Command"
risk_score = 5
rule_id = "20fe6f3e-a906-4552-a4db-2dda9518ef6b"
severity = "high"
type = "eql"

query = '''
any where process.executable == "C:\\Windows\\System32\\netsh.exe" and 
        process.command_line like~ "*interface show interface*"
'''
