[metadata]
creation_date = "2024/09/21"
maturity = "development"
updated_date = "2024/09/21"

[rule]
author = ["sa"]
description = "new"
language = "eql"
name = "name"
risk_score = 5
rule_id = "20fe6f3e-a906-4552-a4db-2dda9518ef6b"
severity = "high"
type = "eql"

query = '''
network where event.action == "login" and event.outcome == "failure"
'''

