name: Rule Validation and BAS Test

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_commands:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install requirements (if needed)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Step 4: Validate detection rule in custom directory
      - name: Validate Detection Rules
        run: |
          python -m detection_rules validate-rule dac_custom_rules_dir

      # Step 5: Import rules into Kibana with overwrite
      - name: Import Rules into Kibana
        run: |
          python -m detection_rules kibana import-rules --overwrite -e -ac

      # Step 6: Run the custom BAS Test Script
      - name: Run BAS Test Script
        run: |
          c:/Users/stann/Coding_Projects/detection-rules/env/Scripts/python.exe c:/Users/stann/Coding_Projects/Scripts/detection-rules/Create_BAS_Test.py
