name: Rule Validation

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_commands:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Validate detection rule in custom directory
      - name: Validate Detection Rules
        run: |
          python -m detection_rules validate-rule dac_custom_rules_dir/newrule.toml

      # Step 5: Import rules into Kibana with overwrite
      - name: Import Rules into Kibana
        run: |
          python -m detection_rules kibana import-rules --overwrite -e -ac
